name: Android CI

on:
  push:
    branches: [ feature/phone-vertical ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x TVBoxPhone/gradlew
      
    - name: Build with Gradle
      run: cd TVBoxPhone && ./gradlew :phone-android:assembleDebug --no-daemon --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: TVBoxPhone/phone-android/build/outputs/apk/debug/*.apk